services:
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    volumes:
      - ./datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    ports:
      - 3000:3000 # Grafana