namespaces:
- name: quarkus
  regions:
  - aws-eu-west-2
  retention: 1

identities:
- id: quarkus-writer
  type: sa
  api_key:
    generate: true
    expiry_time: 2025-04-01T00:00:00Z
  roles:
    global: read
    namespaces:
      quarkus:  write
- id: quarkus-reader
  type: sa
  roles:
    global: read
    namespaces:
      quarkus:  read

nexus:
- endpoint_name: quarkus-endpoint
  description: |
    My description
  target:
    namespace: quarkus
    task_queue: quarkus-task-queue